### PR TITLE
Inline (and optimize) images

### PR DESCRIPTION
**Pull request by as-com**
Inlined images are much faster to load and do not require you to host the images separately.

### CODE REVIEW

**Comment by tjvr** [comment]
Thanks for this suggestion!

Please could you give/link to an extended summary of the benefits/downsides of inline images? :-)

**Comment by as-com** [comment]
http://dataurl.net/#about

None of the disadvantages seem to be problems. I optimized the images so
they are much smaller than the rather bloated ones.

**Comment by tjvr** [comment]
> I optimized the images so
> they are much smaller than the rather bloated ones.

What sort of optimisation? Did you compress them or reduce the filesize?

Would SVGs be better?

**Comment by as-com** [comment]
I ran the images through ImageOptim which compresses images losslessly. It
removes extraneous information from the image and reduces the file size.

For tiny images like these, SVG tends to be larger than well-optimized PNGs.

**Comment by tjvr** [comment]
That sounds excellent! I'd like to merge this.

Please could you make the change directly in the source file — `scratchblocks2.less` — rebuild, and then update this PR? Thank you! (See [src/Dev-Readme.md](https://github.com/tjvr/scratchblocks/blob/master/src/Dev-Readme.md) for more information.)

> For tiny images like these, SVG tends to be larger than well-optimized PNGs.

I've heard that too. Oh, and base64 SVGs are a pain :(

I suppose what I really want is to replace the arrows with proper retina + transparent PNGs. Fancy doing that too? :-)

**Comment by as-com** [comment]
#87

**Comment by tjvr** [comment]
(FWIW, when using GitHub in future, you don't have to create a new PR; you can update the old one by pushing additional commits to the branch :-))

**Comment by as-com** [comment]
I just didn't want to clobber the repo with outdated/useless commits. :smile:

**Comment by tjvr** [comment]
Aha (thanks)!

The thing to do in that case is to rewrite history via `git rebase` or `git commit -- amend`, and then force-push the branch. (You shouldn't force-push to master, but doing it to PR branches is encouraged!) But of course don't worry about it now :)

**Pull request closed without merging**
