### PR TITLE
Rebuild translations

### PR DESCRIPTION
**Pull request by andylolz**
Refs CodeClub/CodeClubWorld-Projects#69.

### CODE REVIEW

**Comment by andylolz** [comment]
Ahh… I wonder if this is really necessary. Is it better to just fix this in https://github.com/scratchblocks/scratchblocks.github.io ?

**Comment by tjvr** [comment]
Fixing here is still good; it means eventually the Scratch Forums will get updated. And Scratch Wikis for other languages use the plugin too.

**Comment by andylolz** [comment]
Cool, okay. I’m a biiiit suspicious about this PR… `"ignorelt": [null]` appears a lot of times. Also, lots of Lego-related strings are removed.

**Comment by tjvr** [comment]
Hi! Sorry for taking so long to get around to looking at this. Life gets busy!

I used [json-diff](https://github.com/andreyvit/json-diff) to check, something like this:

    $ git checkout master -- translations.js translations-all.js
    $ git reset
    $ mv translations.js translations1.js
    $ mv translations-all.js translations-all1.js
    $ git checkout -- translations.js translations-all.js
    $ sed -E 's/scratchblocks2.[^ ]+ = //' translations.js | sed -E 's/;$//' > translations2.js
    $ sed -E 's/scratchblocks2.[^ ]+ = //' translations-all.js | sed -E 's/;$//' > translations-all2.js
    $ json-diff translations{1,2}.js

I agree with you about the `ignorelt: null` and the Lego-related strings. I did a rebuild myself, and it seems to be a bit better now; maybe the translations changed in the last four months? :-)

Thanks!

**Pull request merged**
