### PR TITLE
SVG renderer

### LINKED ISSUE #8: Bottoms of C blocks
The lengths of the bottoms of C blocks do not match the lengths of their tops and are too short.

---

> screenshot 91
> 
> Technically, the bottom of C blocks should extend as far as the top does.
> 
> http://blob8108.github.com/scratchblocks2/#define%20dance%20(speed)%20%0Aset%20%5Bdist%20v%5D%20to%20((speed)%20*%20(distance%20to%20%5Bmouse-pointer%20v%5D))%0Arepeat%20until%20((timer)%20%3E%20%5B10%5D)%0A%20%20%20%20play%20note%20(42%20v)%20for%20(0.5)%20beats%0Aend%20%2F%2F%20.------------%3E

### PR DESCRIPTION
**Pull request by tjvr**
For #89.

Fixes #8, #17, #23.

Not ready yet; just making a PR to show progress.

Previously: `scratchblocks2.{js,css}` + `block_images` weighed ~65K minified (18K gzipped).
The new `scratchblocks.js` weighs ~45K minified (13K gzipped).

### CODE REVIEW

**Comment by tjvr** [comment]
Fixes #8, #17, #23

**Comment by tjvr** [comment]
I think this is good enough to merge :-)

**Comment by tjvr** [comment]
New readme image:
screen shot 2016-04-09 at 15 49 41

**Comment by liam4** [comment]
Wait, why is the `timer > 10` predicate round..?

**Comment by tjvr** [comment]
@liam4 Because I was blindly transcribing the original! Good catch, thanks :)

**Pull request merged**
