### PR TITLE
Rewrite parser

### PR DESCRIPTION
**Pull request by tjvr**
For #90. :D

Still to do:

- [x] Definitions
- [x] Rings
- [x] Embedded scripts (`{}`)
- [x] Decide what to do about whitespace
- [ ] Translations
- [ ] RTL?

### CODE REVIEW

**Comment by tjvr** [comment]
I've found a really fascinating failure mode!
screen shot 2016-04-10 at 19 50 10

**Comment by liam4** [comment]
This doesn't look quite right.. :)

screen shot 2016-04-10 at 7 23 26 pm

**Comment by tjvr** [comment]
@liam4 Looks fine to me. Your dev setup must be wrong?

**Comment by liam4** [comment]
Hmm. It seems to be fixed :P

**Comment by tjvr** [comment]
This looks ready to merge now!

**Pull request merged**
