### PR TITLE
Added postRenderScript hook

### PR DESCRIPTION
**Pull request by Hardmath123**
For sb2backpack, eventually.

### CODE REVIEW

**Comment by tjvr** [comment]
@Hardmath123 Are you still interested in working on this? If so, we should chat sometime.

**Comment by Hardmath123** [comment]
If by "this" you mean the backpack-addinator, sure. I think it works, it was just waiting for you to merge this PR, and then you and I both forgot about it for the next, uh, two years. :P

We should chat, yeah.

**Comment by tjvr** [comment]
> you and I both forgot about it for the next, uh, two years. :P

Indeed; oops :P

Hmm. I'd suggest putting the hook after the `$container` line, in case you want to do more exciting things in the future :-) Also as a really minor style point, could we extract `scripts[i]` to a variable?

Otherwise, I don't see a problem with this. I shall merge it post-haste, after these fixes!

**Comment by tjvr** [comment]
Since the API is changing slightly for v3, I'm going to move this to a fresh issue.

By I think a function passed in `options` is roughly the right thing to do.

**Pull request closed without merging**
