### PR TITLE
Add SVG rings

### PR DESCRIPTION
**Pull request by tjvr**
For #97.

### CODE REVIEW

**Comment by tjvr** [comment]
An example script:
```
say (x position)
call (function)
call ({} ▸ :: grey ring) :: control
call (() ▸ :: grey ring) :: control
call (<> ▸ :: grey ring) :: control
call ({stamp} ▸ :: grey ring) with inputs [1] [2] [3] :: control
call ({move (10) steps} ▸ :: grey ring) :: control
call ((() × () :: operators) ▸ :: grey ring) with inputs [1] [2] [3] :: control
call ((() + (() + (() + ()))) ▸ :: grey ring) :: control
call (<not <>> ▸ :: grey ring) with inputs [1] [2] [3] :: control
call (<> input names: (a) (b) ◂▸ :: grey ring) :: control
call (<not <(a) = (b)>> input names: (a) (b) :: grey ring) :: control
```

**Comment by tjvr** [comment]
@liam4 Since you seem to be GitHub-stalking me, feel free to test this. Thanks. :P

**Comment by liam4** [comment]
Looks good!



I did notice that left arrows are a lot smaller than right arrows. Might just be because of my computer though. That's also just part of the scratchblocks, i.e.

```
call (<> input names: (a) (b) ◂▸ :: grey ring) :: control
```

so maybe use a different character?

Personally I think it'd be interesting if there were some token that got replaced with the appropriate icon..

```
(<> input names: (a) (b) $icon_left_arrow $icon_right_arrow :: grey ring)
```

**Comment by tjvr** [comment]
> some token that got replaced with the appropriate icon

Yeah, I was wondering about doing something like that. Probably when I release the new parser. :)

Thanks for looking!

**Pull request merged**
